version: '3.1'
services:
  face_detection:
    build: ./algorithm_api/face_detection
    volumes:
      - ../algorithm_api/face_detection:/work
    ports:
      - "20001:20001"
    expose:
      - "20001"