version: '3.1'
services:
  my_redis:
    build: ./my_redis
    ports:
      - "6379:6379"

  my_zookeeper:
    build: ./my_zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: "none"

  my_kafka:
    build: ./my_kafka
    ports:
      - "9092:9092"
    restart: always
    logging:
      driver: "none"
    depends_on:
      - my_zookeeper
    links:
      - my_zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: my_zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: my_kafka
#      KAFKA_CREATE_TOPICS: "user_queue:1:1"

  my_mongo:
    build: ./my_mongo
    volumes:
      - "../mongo_db:/data/db"
    logging:
      driver: "none"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_root
      MONGO_INITDB_ROOT_PASSWORD: my_123456

  face_calculator:
    build: ./face_calculator
    volumes:
      - ../face_calculator:/work
    depends_on:
      - my_kafka
      - my_redis
      - my_zookeeper
    links:
      - face_web
      - face_storage

  face_web:
    build: ./face_web
    ports:
      - "12349:12349"
    volumes:
      - ../face_web:/work
    expose:
      - "12349"
    links:
      - my_mongo
      - my_kafka
      - face_storage

  face_storage:
    build: ./face_storage
    ports:
      - "12350:12350"
    volumes:
      - ../face_storage:/work
    expose:
      - "12350"

  face_collector:
    build: ./face_collector
    volumes:
      - ../face_collector:/work
    links:
      - my_redis
      - my_mongo

  face_request_db:
    build: ./face_request_db
    volumes:
      - ../face_request_db:/work
    links:
      - my_kafka
      - my_mongo
    depends_on:
      - my_kafka
      - my_mongo
      - my_zookeeper