version: '3.1'
services:
  my_redis:
    build: ./my_redis
    ports:
      - "6379:6379"

  my_zookeeper:
    build: ./my_zookeeper
    ports:
      - "2181:2181"

  my_kafka:
    build: ./my_kafka
    ports:
      - "9092:9092"
    links:
      - my_zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: my_zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: my_kafka
#      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_LISTENERS: PLAINTEXT://:9092
  my_mongo:
    build: ./my_mongo
    volumes:
      - "../mongo_db:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_root
      MONGO_INITDB_ROOT_PASSWORD: my_123456

  result_service:
    build: ./result_service
    links:
      - my_redis
      - my_mongo

  fr_service:
    build: ./fr_service
    volumes:
      - ./fr_service:/work
    links:
      - my_redis
      - my_kafka

  my_web:
    build: ./my_web
    ports:
      - "12349:12349"
    volumes:
      - ./my_web:/home
    expose:
      - "12349"
    links:
      - my_redis
      - my_mongo
      - my_kafka
