version: '3.1'
services:
  my_redis:
    build: ./my_redis
    ports:
      - "6379:6379"
#  my_mongo:
#    build: ./my_mongo
#    volumes:
#      - "../mongo_db:/data/db"
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: my_root
#      MONGO_INITDB_ROOT_PASSWORD: my_123456
