version: '3.1'
services:
  face_detection:
    build: ./algorithm_api/face_detection
    volumes:
      - ../algorithm_api/face_detection:/work
    ports:
      - "20001:20001"
    expose:
      - "20001"
    networks:
      - face_services

  face_calculator:
    build: ./face_calculator
    volumes:
      - ../face_calculator:/work
    networks:
      - face_services

  speaker_calculator:
    build: ./speaker_calculator
    volumes:
      - ../speaker_calculator:/work
    networks:
      - face_services

  face_web:
    build: ./face_web
    ports:
      - "12349:12349"
    volumes:
      - ../face_web:/work
    expose:
      - "12349"
    networks:
      - face_services


  face_storage:
    build: ./face_storage
    ports:
      - "12350:12350"
    volumes:
      - ../face_storage:/work
    expose:
      - "12350"
    networks:
      - face_services

  face_collector:
    build: ./face_collector
    volumes:
      - ../face_collector:/work
    networks:
      - face_services

  face_request_db:
    build: ./face_request_db
    volumes:
      - ../face_request_db:/work
    networks:
      - face_services

networks:
  face_services:
    external: true